services:
  - type: web
    name: whatsapp-bot-zona-repuestera
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    disk:
      name: chatbot-data
      mountPath: /opt/render/project/src/data/persistent
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
