services:
  - type: web
    name: whatsapp-bot-zona-repuestera
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /webhook
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
